<?php

/**
 * @file
 * Views vertical_tabs style plugin code.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element\VerticalTabs;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Form\FormState;

/**
 * Implements hook_preprocess_HOOK() for theme_views_view_vertical_tabs().
 */
function template_preprocess_animate_slider_style(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
    
  $view = $variables['view'];
  
  $item = $variables['rows'];
  
  $style = $view->style_plugin;
  $options = $style->options;
  
  $variables['image'] = $item->image;
  $variables['caption'] = $item->caption;
  $variables['data'] = $item->data;
  
  //$count_rows = count($item);
  
  $count_rows = count($view->result);
  
  $field_labels = $view->display_handler->getFieldLabels(TRUE);
  $field_labels = array_keys($field_labels);
  
  $settings = [];
  
  $settings['$AutoPlay'] = ($options['global']['autoplay']) ? TRUE : FALSE;
  $settings['$Interval'] = isset($options['global']['interval']) ? (int) $options['global']['interval'] : 5000;
  
  for($i=0;$i<count($field_labels);$i++){
  $settings['transitions'][$field_labels[$i]]['$showTransition'] = isset($options[$field_labels[$i]]['show_transition']) ? $options[$field_labels[$i]]['show_transition'] : 'slideInLeft';
  $settings['transitions'][$field_labels[$i]]['$hideTransition'] = isset($options[$field_labels[$i]]['hide_transition']) ? $options[$field_labels[$i]]['hide_transition'] : 'slideOutLeft';
  }
  $settings['field_labels'] = $field_labels;
  
  $settings['count_rows'] = $count_rows;

  $view->element['#attached']['drupalSettings']['views']['animateSlider'] = $settings;
           
//  $style = $view->style_plugin;
//  $options = $style->options;
//  $group = $view->storage->id() . '-' . $view->current_display;
//  
   $view->element['#attached']['library'][] = 'animate_slider/animate_slider';

}
