<?php

/**
 * @file
 * Views Animate Slider style plugin code.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element\VerticalTabs;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Form\FormState;

/**
 * Implements hook_preprocess_HOOK() for theme_animate_slider_style().
 */
function template_preprocess_animate_slider_style(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
    
  $view = $variables['view'];
  $item = $variables['rows'];
  
  $style = $view->style_plugin;
  $options = $style->options;

  $variables['data'] = $item->renderData;

  $count_rows = count($view->result);
  
  $field_labels = array_keys($view->display_handler->getFieldLabels(TRUE));
  
  $settings = [];
  
  $settings['autoplay'] = isset($options['global']['autoplay']) ? TRUE : FALSE;
  $settings['interval'] = isset($options['global']['interval']) ? (int) $options['global']['interval'] : 5000;

  for($i=0;$i<count($field_labels);$i++){
      
  $settings['transitions'][$field_labels[$i]]['$showTransition'] = isset($options[$field_labels[$i]]['show_transition']) ? $options[$field_labels[$i]]['show_transition'] : 'slideInLeft';
  $settings['transitions'][$field_labels[$i]]['$hideTransition'] = isset($options[$field_labels[$i]]['hide_transition']) ? $options[$field_labels[$i]]['hide_transition'] : 'slideOutLeft';
  $settings['transitions'][$field_labels[$i]]['delay'] = isset($options[$field_labels[$i]]['delay']) ?(int)$options[$field_labels[$i]]['delay'] : 1;
  }
  $settings['field_labels'] = $field_labels;
  
  $settings['count_rows'] = $count_rows;

  $view->element['#attached']['drupalSettings']['views']['animateSlider'] = $settings;
           
  $view->element['#attached']['library'][] = 'animate_slider/animate_slider';

}